# Generated by Django 6.0.7 on 2026-08-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_products/'),
        ),
    ]
