# Generated by Django 6.0.7 on 2026-08-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_custom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('original', 'Original'), ('magic-masala', 'Magic Masala'), ('spicy', 'Spicy'), ('combo', 'Combo')], default='original', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
