# Generated by Django 6.0.7 on 2026-08-05 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_combo_name_cartitem_combo_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='combos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packets', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='combo_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='combo_size',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.combo'),
        ),
    ]
