# Generated by Django 6.0.7 on 2026-08-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_combo_remove_cartitem_combo_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='combo',
            name='badge',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('BEST VALUE', 'BEST VALUE'), ('FAMILY', 'FAMILY'), ('LIMITED', 'LIMITED')], default='NORMAL', max_length=30),
        ),
        migrations.AddField(
            model_name='combo',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=100),
        ),
        migrations.AddField(
            model_name='combo',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='feature_1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='feature_2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='feature_3',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='feature_4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='combo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combo',
            name='weight',
            field=models.PositiveIntegerField(help_text='Example: 300'),
        ),
    ]
