# Generated by Django 6.0.7 on 2026-08-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_combo_options_combo_badge_combo_button_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='feature_1',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='feature_2',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='combo',
            name='feature_4',
        ),
        migrations.AddField(
            model_name='combo',
            name='features',
            field=models.TextField(default=1, help_text='\nWrite one feature per line.\n\nExample\n\n3 Premium Banana Chips\nFreshly Prepared\nFree Delivery\nBest Value\n'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='combo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='combo',
            name='weight',
            field=models.PositiveIntegerField(help_text='Example : 300'),
        ),
    ]
