# Generated by Django 6.0.7 on 2026-08-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_limited_edition', models.BooleanField(default=True)),
                ('limited_badge', models.CharField(blank=True, default='LIMITED EDITION', max_length=50, verbose_name='Limited Edition Badge')),
                ('limited_stock', models.PositiveIntegerField(default=0, verbose_name='Limited Edition Stock')),
                ('limited_description', models.TextField(blank=True, verbose_name='Limited Edition Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Limited Edition',
                'verbose_name_plural': 'Limited Editions',
                'ordering': ['-created_at'],
            },
        ),
    ]
