# Generated by Django 6.0.7 on 2026-08-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LimitedEdition',
        ),
    ]
