# Generated by Django 6.0.7 on 2026-09-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_limitededition'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenuBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Premium Banana Chips', max_length=200)),
                ('subtitle', models.CharField(default='Fresh • Crunchy • Healthy', max_length=200)),
                ('image', models.ImageField(upload_to='mega_menu/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(default='/products/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
